name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install  # Install dependencies

      - name: Build project
        run: npm run build  # Build the project

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Ensure v4 is used
        with:
          name: production-files
          # No path specified, automatically handles the output from the build process

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          # No path specified, automatically downloads the artifact

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Ensure v4 is used
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Specify root directory if no build path
