name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Will run on Node.js 20 automatically

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Explicitly using Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: production-files
          path: ./dist # Assuming default build directory

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Ensuring Node.js 20 during deploy steps

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Upgrade to v4 for Node.js 20 support
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust according to your output directory
